// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://opghuyjdrfoqsymoyjjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wZ2h1eWpkcmZvcXN5bW95ampxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MTgyMzYsImV4cCI6MjA2OTI5NDIzNn0.MmV2nbvnX-WKBgaX1aro-0Jp4VKUxpF4HF8lJZamKOA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});